In [ ]:
import pandas as pd
import numpy as np
import geopandas as gpd
%pip install openpyxl
import openpyxl

In [2]:
gen_df = pd.read_excel("IIC_CSBP_D3_Enrollments-Graduates_2019-2022.xlsx", sheet_name="GEN")
gen_df.head()

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [24]:
imm_df = pd.read_excel("IIC_CSBP_D3_Enrollments-Graduates_2019-2022.xlsx", sheet_name="IMM")
imm_df.head()

,ISCED Level of Education,Credential Type,CIP6 Code,CIP Name,PR code,PRdguid,Province or Territory,Academic Year,Value,Enrollment Type,Source Sheet,Institution,CMAuid,CMAname,CSDuid,CSDname
0,Post-secondary non-tertiary education,Certificate,12.0407,Hair styling/stylist and hair design,10,2021A000210,Newfoundland and Labrador,2019_2020,24,IMM,BHASE_IMM_ENROLL_PROV,NaN,NaN,NaN,NaN,NaN
1,Post-secondary non-tertiary education,Certificate,12.0500,"Cooking and related culinary arts, general (ex...",10,2021A000210,Newfoundland and Labrador,2019_2020,54,IMM,BHASE_IMM_ENROLL_PROV,NaN,NaN,NaN,NaN,NaN
2,Post-secondary non-tertiary education,Certificate,12.0501,Baking and pastry arts/baker/pastry chef,10,2021A000210,Newfoundland and Labrador,2019_2020,6,IMM,BHASE_IMM_ENROLL_PROV,NaN,NaN,NaN,NaN,NaN
3,Post-secondary non-tertiary education,Certificate,19.0709,Child care provider/assistant,10,2021A000210,Newfoundland and Labrador,2019_2020,237,IMM,BHASE_IMM_ENROLL_PROV,NaN,NaN,NaN,NaN,NaN
4,Post-secondary non-tertiary education,Certificate,21.0101,Pre-technology education/pre-industrial arts p...,10,2021A000210,Newfoundland and Labrador,2019_2020,15,IMM,BHASE_IMM_ENROLL_PROV,NaN,NaN,NaN,NaN,NaN

In [14]:
def clean_data(df):
    # Drop columns: 'CIP6 Code', 'Province or Territory' and 4 other columns
    df_clean = (df
          .drop(columns=['CIP6 Code', 'Province or Territory', 'Enrollment Type', 'CMAname', 'CSDname'])
          .rename(columns={'Source Sheet': 'STEM/BHASE'})
          .astype({' PR code': 'category', 
                   'ISCED Level of Education': 'category', 
                   'Credential Type': 'category', 
                   'CIP Name': 'category', 
                   'PRdguid': 'category', 
                   'Academic Year': 'category', 
                   'STEM/BHASE': 'category', 
                   'Institution': 'category', 
                   'CMAuid': 'category', 
                   'CSDuid': 'category'})
    )
    df_clean['STEM/BHASE'] = (df_clean['STEM/BHASE']
                        .str.replace("^BHASE\\w+?$", "BHASE", case=False, regex=True)
                        .str.replace("^STEM\\w+?$", "STEM", case=False, regex=True)
    )
    df_clean['Value'] = df_clean['Value'].replace("..", np.nan).astype('float').astype('Int32')

    return df_clean

gen_df_clean = clean_data(gen_df)
imm_df_clean = clean_data(imm_df)
gen_df_clean.head()

C:\Users\SamuelMorency\AppData\Local\Temp\ipykernel_21492\481123872.py:21: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean['Value'] = df_clean['Value'].replace("..", np.nan).astype('float').astype('Int32')
C:\Users\SamuelMorency\AppData\Local\Temp\ipykernel_21492\481123872.py:21: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_clean['Value'] = df_clean['Value'].replace("..", np.nan).astype('float').astype('Int32')

,ISCED Level of Education,Credential Type,CIP Name,PR code,PRdguid,Academic Year,Value,STEM/BHASE,Institution,CMAuid,CSDuid
0,Post-secondary non-tertiary education,Certificate,Hair styling/stylist and hair design,10,2021A000210,2019_2020,<NA>,BHASE,NaN,NaN,NaN
1,Post-secondary non-tertiary education,Certificate,"Cooking and related culinary arts, general (ex...",10,2021A000210,2019_2020,42,BHASE,NaN,NaN,NaN
2,Post-secondary non-tertiary education,Certificate,Baking and pastry arts/baker/pastry chef,10,2021A000210,2019_2020,3,BHASE,NaN,NaN,NaN
3,Post-secondary non-tertiary education,Certificate,Child care provider/assistant,10,2021A000210,2019_2020,3,BHASE,NaN,NaN,NaN
4,Post-secondary non-tertiary education,Certificate,Pre-technology education/pre-industrial arts p...,10,2021A000210,2019_2020,9,BHASE,NaN,NaN,NaN

In [15]:
imm_df_clean.head()

,ISCED Level of Education,Credential Type,CIP Name,PR code,PRdguid,Academic Year,Value,STEM/BHASE,Institution,CMAuid,CSDuid
0,Post-secondary non-tertiary education,Certificate,Hair styling/stylist and hair design,10,2021A000210,2019_2020,24,BHASE,NaN,NaN,NaN
1,Post-secondary non-tertiary education,Certificate,"Cooking and related culinary arts, general (ex...",10,2021A000210,2019_2020,54,BHASE,NaN,NaN,NaN
2,Post-secondary non-tertiary education,Certificate,Baking and pastry arts/baker/pastry chef,10,2021A000210,2019_2020,6,BHASE,NaN,NaN,NaN
3,Post-secondary non-tertiary education,Certificate,Child care provider/assistant,10,2021A000210,2019_2020,237,BHASE,NaN,NaN,NaN
4,Post-secondary non-tertiary education,Certificate,Pre-technology education/pre-industrial arts p...,10,2021A000210,2019_2020,15,BHASE,NaN,NaN,NaN

In [17]:
gen_level = (gen_df_clean
             .groupby("ISCED Level of Education")
             .agg(graduates=('Value', 'sum'))
             .reset_index()
)
gen_level

C:\Users\SamuelMorency\AppData\Local\Temp\ipykernel_21492\2906797122.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("ISCED Level of Education")

                ISCED Level of Education  graduates
0               Bachelor’s or equivalent    7833756
1                 Doctoral or equivalent     387981
2                 Master’s or equivalent    1716423
3                         Not applicable     427053
4  Post-secondary non-tertiary education    1875288
5         Short-cycle tertiary education    3701547
6              Upper secondary education     152502

In [18]:
imm_level = (imm_df_clean
             .groupby("ISCED Level of Education")
             .agg(graduates=('Value', 'sum'))
             .reset_index()
)
imm_level

C:\Users\SamuelMorency\AppData\Local\Temp\ipykernel_21492\3954845860.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("ISCED Level of Education")

                ISCED Level of Education  graduates
0               Bachelor’s or equivalent    7934007
1                 Doctoral or equivalent     391587
2                 Master’s or equivalent    1744356
3                         Not applicable     464079
4  Post-secondary non-tertiary education    1912218
5         Short-cycle tertiary education    3747567
6              Upper secondary education     158193

In [3]:
data = pd.read_pickle("cleaned_data.pkl")
data

,STEM/BHASE,Province_Territory,CMA_CA,Institution,ISCED_level_of_education,Credential_Type,CIP6_Code,CIP_Name,DGUID,year,value
0,BHASE,Alberta,Athabasca,Athabasca University,Bachelor’s or equivalent,Certificate,13.1007,Education/teaching of individuals with multipl...,2021A00054813048,2019_2020,6
1,BHASE,Alberta,Athabasca,Athabasca University,Bachelor’s or equivalent,Certificate,13.1007,Education/teaching of individuals with multipl...,2021A00054813048,2020_2021,15
2,BHASE,Alberta,Athabasca,Athabasca University,Bachelor’s or equivalent,Certificate,13.1007,Education/teaching of individuals with multipl...,2021A00054813048,2021_2022,6
3,BHASE,Alberta,Athabasca,Athabasca University,Bachelor’s or equivalent,Degree (includes applied degree),4.0201,"Architecture (BArch, BA, BS, BSc, MArch, MA, M...",2021A00054813048,2019_2020,3
4,BHASE,Alberta,Athabasca,Athabasca University,Bachelor’s or equivalent,Degree (includes applied degree),4.0201,"Architecture (BArch, BA, BS, BSc, MArch, MA, M...",2021A00054813048,2020_2021,0
...,...,...,...,...,...,...,...,...,...,...,...
53306,STEM,Yukon,Whitehorse,Yukon College,Short-cycle tertiary education,Diploma,30.0101,Biological and physical sciences,2021S0504990,2020_2021,3
53307,STEM,Yukon,Whitehorse,Yukon University,Bachelor’s or equivalent,Degree (includes applied degree),30.0101,Biological and physical sciences,2021S0504990,2021_2022,6
53308,STEM,Yukon,Whitehorse,Yukon University,Short-cycle tertiary education,Certificate,30.0101,Biological and physical sciences,2021S0504990,2021_2022,3
53309,STEM,Yukon,Whitehorse,Yukon University,Short-cycle tertiary education,Diploma,15.9999,Engineering technologies and engineering-relat...,2021S0504990,2021_2022,0
53310,STEM,Yukon,Whitehorse,Yukon University,Short-cycle tertiary education,Diploma,30.0101,Biological and physical sciences,2021S0504990,2021_2022,0

In [33]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(data):
    # Drop columns: 'STEM/BHASE', 'Province_Territory' and 8 other columns
    data = data.drop(columns=['STEM/BHASE', 'Province_Territory', 'CMA_CA', 'Institution', 'ISCED_level_of_education', 'Credential_Type', 'CIP6_Code', 'CIP_Name', 'year', 'value'])
    # Drop duplicate rows across all columns
    data = data.drop_duplicates()
    return data

data_clean = clean_data(data.copy())
data_clean

dguids = data_clean['DGUID'].to_list()
dguids

['2021A00054813048',
 '2021A00054817027',
 '2021S0503825',
 '2021S0503835',
 '2021S0504850',
 '2021A00054812037',
 '2021S0504832',
 '2021S0503810',
 '2021S0504805',
 '2021A00054806034',
 '2021S0503830',
 '2021A00054810042',
 '2021S0504860',
 '2021S0503932',
 '2021A00055903058',
 '2021S0504943',
 '2021S0504905',
 '2021S0504975',
 '2021S0503925',
 '2021S0503915',
 '2021A00055933006',
 '2021S0503938',
 '2021S0504970',
 '2021S0504965',
 '2021S0503933',
 '2021S0503935',
 '2021S0504610',
 '2021S0504605',
 '2021S0503602',
 '2021A00054602032',
 '2021A00054621045',
 '2021S0504328',
 '2021S0503320',
 '2021S0503305',
 '2021A00051307008',
 '2021S0503001',
 '2021A00051004019',
 '2021A00056105001',
 '2021A00051214002',
 '2021S0504225',
 '2021A00051203001',
 '2021S0503205',
 '2021A00051207024',
 '2021A00056204003',
 '2021S0503568',
 '2021S0503522',
 '2021S0503543',
 '2021S0504556',
 '2021S0503580',
 '2021S0503550',
 '2021S0503537',
 '2021A00053556076',
 '2021S0503521',
 '2021S0503541',
 '2021S0503555',
 '2021S0504575',
 '2021S0504569',
 '2021S0503532',
 '2021S0503505',
 '2021S0503529',
 '2021S0504562',
 '2021S0504590',
 '2021S0503539',
 '2021S0504553',
 '2021S0503595',
 '2021S0504586',
 '2021S0503535',
 '2021S0503559',
 '2021S0504105',
 '2021S0504410',
 '2021S0504406',
 '2021S0503447',
 '2021A00052403005',
 '2021S0504450',
 '2021S0504456',
 '2021S0504403',
 '2021S0503462',
 '2021S0503421',
 '2021S0504404',
 '2021A00052414065',
 '2021S0504405',
 '2021S0504485',
 '2021S0503408',
 '2021A00052491042',
 '2021S0504428',
 '2021S0504452',
 '2021S0504465',
 '2021S0504412',
 '2021S0504444',
 '2021S0503433',
 '2021S0504454',
 '2021S0504430',
 '2021S0503442',
 '2021S0504440',
 '2021S0503705',
 '2021S0503725',
 '2021S0504990']

In [8]:
shape = gpd.read_file("shapes.zip")
shape

c:\code\Infozone\.venv\Lib\site-packages\pyogrio\geopandas.py:265: UserWarning: More than one layer found in 'shapes.zip': 'lcma000b21a_e' (default), 'lcsd000b21a_e', 'lpr_000b21a_e'. Specify layer parameter to avoid this warning.
  result = read_func(

,CMAUID,CMAPUID,DGUID,DGUIDP,CMANAME,CMATYPE,LANDAREA,PRUID,geometry
0,001,10001,2021S0503001,None,St. John's,B,931.5637,10,"MULTIPOLYGON (((8995475.183 2122891.223, 89958..."
1,010,10010,2021S0504010,None,Grand Falls-Windsor,D,54.8429,10,"POLYGON ((8715069.6 2159071.726, 8714819.769 2..."
2,011,10011,2021S0504011,None,Gander,D,2412.6700,10,"POLYGON ((8794489.877 2214683.869, 8795102.377..."
3,015,10015,2021S0504015,None,Corner Brook,D,1122.5751,10,"POLYGON ((8595903.94 2105395.523, 8596208.203 ..."
4,105,11105,2021S0504105,None,Charlottetown,D,1112.4274,11,"MULTIPOLYGON (((8369241.149 1605069.803, 83690..."
...,...,...,...,...,...,...,...,...,...
151,970,59970,2021S0504970,None,Prince George,K,17650.9918,59,"POLYGON ((4402020.851 2453306.74, 4402149.62 2..."
152,975,59975,2021S0504975,None,Dawson Creek,D,11716.7959,59,"POLYGON ((4505598.494 2605104.386, 4507567.426..."
153,977,59977,2021S0504977,None,Fort St. John,D,617.7325,59,"POLYGON ((4521246.88 2592138.491, 4519928.797 ..."
154,990,60990,2021S0504990,None,Whitehorse,D,8465.2077,60,"POLYGON ((4121668.466 3499718.529, 4123760.217..."
155,995,61995,2021S0504995,None,Yellowknife,D,103.3722,61,"POLYGON ((5103227.786 3103418.451, 5100152.189..."

In [9]:
cma = gpd.read_file("lcma000b21a_e.shp")
cma

,CMAUID,CMAPUID,DGUID,DGUIDP,CMANAME,CMATYPE,LANDAREA,PRUID,geometry
0,001,10001,2021S0503001,None,St. John's,B,931.5637,10,"MULTIPOLYGON (((8995475.183 2122891.223, 89958..."
1,010,10010,2021S0504010,None,Grand Falls-Windsor,D,54.8429,10,"POLYGON ((8715069.6 2159071.726, 8714819.769 2..."
2,011,10011,2021S0504011,None,Gander,D,2412.6700,10,"POLYGON ((8794489.877 2214683.869, 8795102.377..."
3,015,10015,2021S0504015,None,Corner Brook,D,1122.5751,10,"POLYGON ((8595903.94 2105395.523, 8596208.203 ..."
4,105,11105,2021S0504105,None,Charlottetown,D,1112.4274,11,"MULTIPOLYGON (((8369241.149 1605069.803, 83690..."
...,...,...,...,...,...,...,...,...,...
151,970,59970,2021S0504970,None,Prince George,K,17650.9918,59,"POLYGON ((4402020.851 2453306.74, 4402149.62 2..."
152,975,59975,2021S0504975,None,Dawson Creek,D,11716.7959,59,"POLYGON ((4505598.494 2605104.386, 4507567.426..."
153,977,59977,2021S0504977,None,Fort St. John,D,617.7325,59,"POLYGON ((4521246.88 2592138.491, 4519928.797 ..."
154,990,60990,2021S0504990,None,Whitehorse,D,8465.2077,60,"POLYGON ((4121668.466 3499718.529, 4123760.217..."
155,995,61995,2021S0504995,None,Yellowknife,D,103.3722,61,"POLYGON ((5103227.786 3103418.451, 5100152.189..."

In [52]:
province_sf = gpd.read_file("hidden/shapes/lpr_000b21a_e.shp")
cma_sf = gpd.read_file("hidden/shapes/lcma000b21a_e.shp")
csd_sf = gpd.read_file("hidden/shapes/lcsd000b21a_e.shp")

to_convert = [province_sf, cma_sf, csd_sf]
converted = [df.to_crs(epsg=4326) for df in to_convert]
province_sf, cma_sf, csd_sf = converted

# Optimize data cleaning with chained operations
cma_longlat_clean = (cma_sf
    .rename(columns={'CMANAME': 'NAME'})
    .drop(columns=['DGUIDP', 'CMAUID', 'CMAPUID','CMATYPE','LANDAREA'])
    #.assign(CLASS="CMA_CA")
)

csd_longlat_clean = (csd_sf
    .rename(columns={'CSDNAME': 'NAME'})
    .drop(columns=['CSDUID','CSDTYPE','LANDAREA'])
    #.assign(CLASS="CSD")
)

combined_longlat = pd.concat([cma_longlat_clean, csd_longlat_clean], ignore_index=True)
combined_longlat_indexed = combined_longlat#.set_index('DGUID')
combined_longlat_clean = combined_longlat_indexed[combined_longlat_indexed['DGUID'].isin(dguids)]
combined_longlat_clean.to_parquet("combined_longlat_clean.parquet")
combined_longlat_clean

,DGUID,NAME,PRUID,geometry
0,2021S0503001,St. John's,10,"MULTIPOLYGON (((-52.77045 47.26722, -52.76782 ..."
4,2021S0504105,Charlottetown,11,"MULTIPOLYGON (((-63.17397 46.12389, -63.1834 4..."
6,2021S0503205,Halifax,12,"MULTIPOLYGON (((-63.74815 44.46934, -63.75085 ..."
10,2021S0504225,Cape Breton,12,"MULTIPOLYGON (((-60.56652 45.95511, -60.57968 ..."
11,2021S0503305,Moncton,13,"MULTIPOLYGON (((-64.49544 46.09204, -64.4933 4..."
...,...,...,...,...
4381,2021A00054817027,Big Lakes County,48,"MULTIPOLYGON (((-115.41229 55.35239, -115.4106..."
4498,2021A00055903058,Central Kootenay J,59,"MULTIPOLYGON (((-117.6533 49.316, -117.64479 4..."
4827,2021A00055933006,Merritt,59,"POLYGON ((-120.73379 50.12761, -120.73391 50.1..."
5275,2021A00056105001,Fort Smith,61,"POLYGON ((-111.81102 60.00005, -112 60, -112.2..."
5287,2021A00056204003,Iqaluit,62,"POLYGON ((-68.61164 63.75031, -68.61607 63.783..."

In [45]:
province_sf

,PRUID,DGUID,PRNAME,PRENAME,PRFNAME,PREABBR,PRFABBR,LANDAREA,geometry
0,10,2021A000210,Newfoundland and Labrador / Terre-Neuve-et-Lab...,Newfoundland and Labrador,Terre-Neuve-et-Labrador,N.L.,T.-N.-L.,3.581704e+05,"MULTIPOLYGON (((-55.92076 52.74286, -55.93074 ..."
1,11,2021A000211,Prince Edward Island / Ãle-du-Prince-Ãdouard,Prince Edward Island,Ãle-du-Prince-Ãdouard,P.E.I.,Ã.-P.-Ã.,5.681179e+03,"MULTIPOLYGON (((-63.68516 46.55782, -63.69626 ..."
2,12,2021A000212,Nova Scotia / Nouvelle-Ãcosse,Nova Scotia,Nouvelle-Ãcosse,N.S.,N.-Ã.,5.282471e+04,"MULTIPOLYGON (((-64.00918 44.52685, -64.00194 ..."
3,13,2021A000213,New Brunswick / Nouveau-Brunswick,New Brunswick,Nouveau-Brunswick,N.B.,N.-B.,7.124850e+04,"MULTIPOLYGON (((-68.71641 47.24189, -68.7275 4..."
4,24,2021A000224,Quebec / QuÃ©bec,Quebec,QuÃ©bec,Que.,Qc,1.298600e+06,"MULTIPOLYGON (((-73.84009 45.33841, -73.85112 ..."
5,35,2021A000235,Ontario,Ontario,Ontario,Ont.,Ont.,8.924118e+05,"MULTIPOLYGON (((-94.47507 49.58741, -94.46954 ..."
6,46,2021A000246,Manitoba,Manitoba,Manitoba,Man.,Man.,5.403102e+05,"MULTIPOLYGON (((-94.65029 58.93643, -94.64883 ..."
7,47,2021A000247,Saskatchewan,Saskatchewan,Saskatchewan,Sask.,Sask.,5.770604e+05,"POLYGON ((-102 60, -102.00739 59.75178, -102.0..."
8,48,2021A000248,Alberta,Alberta,Alberta,Alta.,Alb.,6.346583e+05,"POLYGON ((-110.00502 48.9997, -110.27157 48.99..."
9,59,2021A000259,British Columbia / Colombie-Britannique,British Columbia,Colombie-Britannique,B.C.,C.-B.,9.206866e+05,"MULTIPOLYGON (((-132.33996 52.97464, -132.3358..."
10,60,2021A000260,Yukon,Yukon,Yukon,Y.T.,Yn,4.723454e+05,"MULTIPOLYGON (((-139.55565 69.53517, -139.5661..."
11,61,2021A000261,Northwest Territories / Territoires du Nord-Ouest,Northwest Territories,Territoires du Nord-Ouest,N.W.T.,T.N.-O.,1.127712e+06,"MULTIPOLYGON (((-133.11365 68.88023, -133.1313..."
12,62,2021A000262,Nunavut,Nunavut,Nunavut,Nvt.,Nt,1.836994e+06,"MULTIPOLYGON (((-106.40788 68.4527, -106.42855..."

In [50]:
province_longlat = (province_sf
    .rename(columns={'PRENAME': 'NAME'})
    .drop(columns=['PRNAME','PRFNAME','PREABBR','PRFABBR','LANDAREA'])
)

province_longlat_clean = province_longlat#.set_index('DGUID')
province_longlat_clean.to_parquet("province_longlat_clean.parquet")
province_longlat_clean

,PRUID,DGUID,NAME,geometry
0,10,2021A000210,Newfoundland and Labrador,"MULTIPOLYGON (((-55.92076 52.74286, -55.93074 ..."
1,11,2021A000211,Prince Edward Island,"MULTIPOLYGON (((-63.68516 46.55782, -63.69626 ..."
2,12,2021A000212,Nova Scotia,"MULTIPOLYGON (((-64.00918 44.52685, -64.00194 ..."
3,13,2021A000213,New Brunswick,"MULTIPOLYGON (((-68.71641 47.24189, -68.7275 4..."
4,24,2021A000224,Quebec,"MULTIPOLYGON (((-73.84009 45.33841, -73.85112 ..."
5,35,2021A000235,Ontario,"MULTIPOLYGON (((-94.47507 49.58741, -94.46954 ..."
6,46,2021A000246,Manitoba,"MULTIPOLYGON (((-94.65029 58.93643, -94.64883 ..."
7,47,2021A000247,Saskatchewan,"POLYGON ((-102 60, -102.00739 59.75178, -102.0..."
8,48,2021A000248,Alberta,"POLYGON ((-110.00502 48.9997, -110.27157 48.99..."
9,59,2021A000259,British Columbia,"MULTIPOLYGON (((-132.33996 52.97464, -132.3358..."
10,60,2021A000260,Yukon,"MULTIPOLYGON (((-139.55565 69.53517, -139.5661..."
11,61,2021A000261,Northwest Territories,"MULTIPOLYGON (((-133.11365 68.88023, -133.1313..."
12,62,2021A000262,Nunavut,"MULTIPOLYGON (((-106.40788 68.4527, -106.42855..."

In [49]:
combined = gpd.read_parquet("combined_longlat_clean.parquet")
combined

,NAME,PRUID,geometry
DGUID,,,
2021S0503001,St. John's,10,"MULTIPOLYGON (((-52.77045 47.26722, -52.76782 ..."
2021S0504105,Charlottetown,11,"MULTIPOLYGON (((-63.17397 46.12389, -63.1834 4..."
2021S0503205,Halifax,12,"MULTIPOLYGON (((-63.74815 44.46934, -63.75085 ..."
2021S0504225,Cape Breton,12,"MULTIPOLYGON (((-60.56652 45.95511, -60.57968 ..."
2021S0503305,Moncton,13,"MULTIPOLYGON (((-64.49544 46.09204, -64.4933 4..."
...,...,...,...
2021A00054817027,Big Lakes County,48,"MULTIPOLYGON (((-115.41229 55.35239, -115.4106..."
2021A00055903058,Central Kootenay J,59,"MULTIPOLYGON (((-117.6533 49.316, -117.64479 4..."
2021A00055933006,Merritt,59,"POLYGON ((-120.73379 50.12761, -120.73391 50.1..."
2021A00056105001,Fort Smith,61,"POLYGON ((-111.81102 60.00005, -112 60, -112.2..."
2021A00056204003,Iqaluit,62,"POLYGON ((-68.61164 63.75031, -68.61607 63.783..."